version: "3.9"

services:
  core-x-agent:
    build: .
    container_name: core-x-agent
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./training_data:/app/training_data
    env_file:
      - .env
    ports:
      - "8079:8079"
