version: "3.9"
services:
  mcp:
    build: .
    container_name: mcp-llamaindex
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - OPENAI_API_KEY=
    volumes:
      - ./training_data:/app/training_data
    ports:
      - "8088:8088"
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474" # Browser UI
      - "7687:7687" # Bolt protocol
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
