# Create a new index
curl -X PUT 'https://elastic:changeme@localhost:9200/series' -H 'Content-Type: application/json' -d $'{ 
    "mappings": {
        "properties": {
            "film_to_franchise": {
                "type": "join"
                "relations": {
                    "franchise": "film"
                }
            }
        }
    }
}'

# Bulk insert
curl -X PUT 'https://elastic:changeme@localhost:9200/series/_bulk?pretty' -k \
-H 'Content-Type: application/json' --data-binary @series.json

# Search
curl 'https://elastic:changeme@localhost:9200/series/_search?pretty' -k \
-H 'content-type: application/x-ndjson' -d $'{ 
    "query": {
        "has_parent": {
            "parent_type": "franchise",
            "query": {

            }
        }
    }
}'
# Search
curl 'https://elastic:changeme@localhost:9200/series/_search?pretty' -k \
-H 'content-type: application/x-ndjson' -d $'{ 
    "query": {
        "has_child": {
            "type": "film",
            "query": {

            }
        }
    }
}'